with source as (
      select * from {{ source('kmv', 'consolidated_open_v') }}
),
renamed as (
    select
        {{ adapter.quote("country_id") }},
        {{ adapter.quote("company_code") }},
        {{ adapter.quote("document_type") }},
        {{ adapter.quote("document_number") }},
        {{ adapter.quote("document_item_number") }},
        {{ adapter.quote("order_number") }},
        {{ adapter.quote("order_item_number") }},
        {{ adapter.quote("document_date_id") }},
        {{ adapter.quote("soldto_customer_id") }},
        {{ adapter.quote("shipto_customer_id") }},
        {{ adapter.quote("payer_customer_id") }},
        {{ adapter.quote("product_id") }},
        {{ adapter.quote("order_type_id") }},
        {{ adapter.quote("rrc_quantity_ordered") }},
        {{ adapter.quote("rrc_quantity_delivered") }},
        {{ adapter.quote("rrc_quantity_invoiced") }},
        {{ adapter.quote("rrc_quantity_bad") }},
        {{ adapter.quote("rc_quantity_ordered") }},
        {{ adapter.quote("rc_quantity_delivered") }},
        {{ adapter.quote("rc_quantity_invoiced") }},
        {{ adapter.quote("rc_quantity_bad") }},
        {{ adapter.quote("oz8_quantity_ordered") }},
        {{ adapter.quote("oz8_quantity_delivered") }},
        {{ adapter.quote("oz8_quantity_invoiced") }},
        {{ adapter.quote("oz8_quantity_bad") }},
        {{ adapter.quote("liter_quantity_ordered") }},
        {{ adapter.quote("liter_quantity_delivered") }},
        {{ adapter.quote("liter_quantity_invoiced") }},
        {{ adapter.quote("liter_quantity_bad") }},
        {{ adapter.quote("piece_quantity_ordered") }},
        {{ adapter.quote("piece_quantity_delivered") }},
        {{ adapter.quote("piece_quantity_invoiced") }},
        {{ adapter.quote("piece_quantity_bad") }},
        {{ adapter.quote("kg_quantity_ordered") }},
        {{ adapter.quote("kg_quantity_delivered") }},
        {{ adapter.quote("kg_quantity_invoiced") }},
        {{ adapter.quote("kg_quantity_bad") }},
        {{ adapter.quote("net_value_local_ordered") }},
        {{ adapter.quote("net_value_local_delivered") }},
        {{ adapter.quote("net_value_local_invoiced") }},
        {{ adapter.quote("net_value_local_bad") }},
        {{ adapter.quote("net_value_czk_ordered") }},
        {{ adapter.quote("net_value_czk_delivered") }},
        {{ adapter.quote("net_value_czk_invoiced") }},
        {{ adapter.quote("net_value_czk_bad") }},
        {{ adapter.quote("gross_revenue_local") }},
        {{ adapter.quote("promo_discount_local") }},
        {{ adapter.quote("customer_discount_local") }},
        {{ adapter.quote("free_goods_discount_local") }},
        {{ adapter.quote("gross_revenue_czk") }},
        {{ adapter.quote("promo_discount_czk") }},
        {{ adapter.quote("customer_discount_czk") }},
        {{ adapter.quote("free_goods_discount_czk") }}

    from source
)
select * from renamed
  