with source as (
      select * from {{ source('sap', 'customer_now_dvt_c_hv') }}
),
renamed as (
    select
        {{ adapter.quote("customer_id") }},
        {{ adapter.quote("customer_logical_id") }},
        {{ adapter.quote("country_id") }},
        {{ adapter.quote("customer_code") }},
        {{ adapter.quote("customer_name_1") }},
        {{ adapter.quote("customer_name_2") }},
        {{ adapter.quote("customer_name_3") }},
        {{ adapter.quote("customer_name_4") }},
        {{ adapter.quote("customer_country_id") }},
        {{ adapter.quote("eu_member_country_flag") }},
        {{ adapter.quote("country_name") }},
        {{ adapter.quote("city") }},
        {{ adapter.quote("zipcode") }},
        {{ adapter.quote("address") }},
        {{ adapter.quote("customer_account_group_code") }},
        {{ adapter.quote("customer_account_group") }},
        {{ adapter.quote("customer_group_code") }},
        {{ adapter.quote("customer_group") }},
        {{ adapter.quote("transportation_zone_code") }},
        {{ adapter.quote("transportation_zone") }},
        {{ adapter.quote("central_order_block_id") }},
        {{ adapter.quote("central_delivery_block_id") }},
        {{ adapter.quote("central_billing_block_id") }},
        {{ adapter.quote("seasonal_customer_code") }},
        {{ adapter.quote("seasonal_customer") }},
        {{ adapter.quote("one_time_account_flag") }},
        {{ adapter.quote("chain_customer_code") }},
        {{ adapter.quote("chain_customer") }},
        {{ adapter.quote("service_type_code") }},
        {{ adapter.quote("service_type") }},
        {{ adapter.quote("default_depot_code") }},
        {{ adapter.quote("default_depot_id") }},
        {{ adapter.quote("distributor_logical_id") }},
        {{ adapter.quote("distributor_id") }},
        {{ adapter.quote("price_group_code") }},
        {{ adapter.quote("price_group") }},
        {{ adapter.quote("sales_channel_id") }},
        {{ adapter.quote("pepsi_club_type_code") }},
        {{ adapter.quote("pepsi_club_type") }},
        {{ adapter.quote("key_account_code") }},
        {{ adapter.quote("key_account") }},
        {{ adapter.quote("region_code") }},
        {{ adapter.quote("region_name") }},
        {{ adapter.quote("county_code") }},
        {{ adapter.quote("county_name") }},
        {{ adapter.quote("city_code") }},
        {{ adapter.quote("city_code_name") }},
        {{ adapter.quote("tax_code_1") }},
        {{ adapter.quote("tax_code_2") }},
        {{ adapter.quote("vat_registration_number") }},
        {{ adapter.quote("operating_permit_number") }},
        {{ adapter.quote("created_on_date") }},
        {{ adapter.quote("modified_on_date") }},
        {{ adapter.quote("changed_by") }},
        {{ adapter.quote("visit_valid_from") }},
        {{ adapter.quote("visit_valid_to") }},
        {{ adapter.quote("visit_suspended_from") }},
        {{ adapter.quote("visit_suspended_to") }},
        {{ adapter.quote("visit_day_1") }},
        {{ adapter.quote("visit_day_2") }},
        {{ adapter.quote("visit_day_3") }},
        {{ adapter.quote("visit_day_4") }},
        {{ adapter.quote("visit_day_5") }},
        {{ adapter.quote("visit_day_6") }},
        {{ adapter.quote("visit_day_7") }},
        {{ adapter.quote("visiting_frequency_id") }},
        {{ adapter.quote("contact_person_code") }},
        {{ adapter.quote("organizational_category_1_code") }},
        {{ adapter.quote("organizational_category_1_description") }},
        {{ adapter.quote("organizational_category_2_code") }},
        {{ adapter.quote("organizational_category_2_description") }},
        {{ adapter.quote("kam_code") }},
        {{ adapter.quote("kam_id") }},
        {{ adapter.quote("payment_term_category_id") }},
        {{ adapter.quote("_name_id") }}

    from source
)
select * from renamed
  