with source as (
      select * from {{ source('sap', 'product_now_dvt_c_hv') }}
),
renamed as (
    select
        {{ adapter.quote("Product_ID") }},
        {{ adapter.quote("Country_ID") }},
        {{ adapter.quote("Product_Logical_ID") }},
        {{ adapter.quote("Beverage_Company_Code") }},
        {{ adapter.quote("Beverage_Company_Name") }},
        {{ adapter.quote("Brand_Code") }},
        {{ adapter.quote("Brand_Name") }},
        {{ adapter.quote("Local_SKU_ID") }},
        {{ adapter.quote("Local_SKU_Name") }},
        {{ adapter.quote("Regional_SKU_Code") }},
        {{ adapter.quote("Regional_SKU_Name") }},
        {{ adapter.quote("Material_Type_Code") }},
        {{ adapter.quote("Material_Type_Name") }},
        {{ adapter.quote("Material_Group_Code") }},
        {{ adapter.quote("Material_Group_ID") }},
        {{ adapter.quote("Material_Group_Name") }},
        {{ adapter.quote("Old_Product_Number") }},
        {{ adapter.quote("Base_Unit_of_Measure_Code") }},
        {{ adapter.quote("Base_Unit_of_Measure_ID") }},
        {{ adapter.quote("Base_Unit_of_Measure_Name") }},
        {{ adapter.quote("Season_Category_Code") }},
        {{ adapter.quote("Season_Category_Name") }},
        {{ adapter.quote("Serving_Type_Code") }},
        {{ adapter.quote("Serving_Type_Name") }},
        {{ adapter.quote("EAN_Code") }},
        {{ adapter.quote("Nielsen_Code") }},
        {{ adapter.quote("PBI_Code") }},
        {{ adapter.quote("Package_Size_Code") }},
        {{ adapter.quote("Package_Size_Name") }},
        {{ adapter.quote("Package_Type_Code") }},
        {{ adapter.quote("Package_Type_Name") }},
        {{ adapter.quote("Case_Size_Code") }},
        {{ adapter.quote("Case_Size_Name") }},
        {{ adapter.quote("Flavour_Code") }},
        {{ adapter.quote("Flavour_Name") }},
        {{ adapter.quote("Flavour_Category_Code") }},
        {{ adapter.quote("Flavour_Category_Name") }},
        {{ adapter.quote("Product_Category_1_Code") }},
        {{ adapter.quote("Product_Category_1_Name") }},
        {{ adapter.quote("Product_Category_2_Code") }},
        {{ adapter.quote("Product_Category_2_Name") }},
        {{ adapter.quote("Product_Category_3_Code") }},
        {{ adapter.quote("Product_Category_3_Name") }},
        {{ adapter.quote("Created_On_Date") }},
        {{ adapter.quote("Modified_On_Date") }},
        {{ adapter.quote("_Name_ID") }}

    from source
)
select * from renamed
  