with source as (
    select * from {{ source('sfa', 'cust_OrdersDataMart') }}
),

renamed as (
    select
        {{ adapter.quote("Country_Code") }},
        {{ adapter.quote("Cust_id") }},
        {{ adapter.quote("MonthID") }},
        {{ adapter.quote("OS_NameL1") }},
        {{ adapter.quote("OS_CodeL1") }},
        {{ adapter.quote("OS_NameL2") }},
        {{ adapter.quote("OS_CodeL2") }},
        {{ adapter.quote("OS_NameL3") }},
        {{ adapter.quote("OS_CodeL3") }},
        {{ adapter.quote("OS_NameL4") }},
        {{ adapter.quote("OS_CodeL4") }},
        {{ adapter.quote("OS_NameL5") }},
        {{ adapter.quote("OS_CodeL5") }},
        {{ adapter.quote("OS_NameL6") }},
        {{ adapter.quote("OS_CodeL6") }},
        {{ adapter.quote("OS_NameL7") }},
        {{ adapter.quote("OS_CodeL7") }},
        {{ adapter.quote("OS_SRStaff") }},
        {{ adapter.quote("Outlet_SWCode") }},
        {{ adapter.quote("Outlet_ERPCode") }},
        {{ adapter.quote("Outlet_LegalName") }},
        {{ adapter.quote("Outlet_LegalAddress") }},
        {{ adapter.quote("Outlet_ActualName") }},
        {{ adapter.quote("Outlet_DeliveryAddress") }},
        {{ adapter.quote("Outlet_Status") }},
        {{ adapter.quote("Outlet_Network") }},
        {{ adapter.quote("Outlet_SubType") }},
        {{ adapter.quote("Outlet_Type") }},
        {{ adapter.quote("Outlet_Group") }},
        {{ adapter.quote("Product_Category") }},
        {{ adapter.quote("Product_Type") }},
        {{ adapter.quote("Product_SWCode") }},
        {{ adapter.quote("Product_Code") }},
        {{ adapter.quote("Product_Name") }},
        {{ adapter.quote("Product_ShortName") }},
        {{ adapter.quote("Product_BarCode") }},
        {{ adapter.quote("Product_PackageQty") }},
        {{ adapter.quote("Visit_Number") }},
        {{ adapter.quote("Visit_Date") }},
        {{ adapter.quote("OrderIntoTheVisit") }},
        {{ adapter.quote("Order_Date") }},
        {{ adapter.quote("Order_Number") }},
        {{ adapter.quote("PaymentForm") }},
        {{ adapter.quote("PaymentFormType") }},
        {{ adapter.quote("Order_Type") }},
        {{ adapter.quote("Warehouse_Code") }},
        {{ adapter.quote("Warehouse_ShortName") }},
        {{ adapter.quote("Warehouse_Name") }},
        {{ adapter.quote("Warehouse_Type") }},
        {{ adapter.quote("Order_Qty") }},
        {{ adapter.quote("Order_PriceWithoutVAT") }},
        {{ adapter.quote("Order_PriceWithVAT") }},
        {{ adapter.quote("Order_SumWithoutVAT") }},
        {{ adapter.quote("Order_SumWithVAT") }},
        {{ adapter.quote("Order_PackageQty") }},
        {{ adapter.quote("Valid_From") }},
        {{ adapter.quote("Valid_To") }}

    from source
)

select * from renamed
