with source as (
      select * from {{ source('sfa', 'dbo_OutLetsCustomField') }}
),
renamed as (
    select
        {{ adapter.quote("Country_Code") }},
        {{ adapter.quote("CustomKey") }} as outlet_id,
        {{ adapter.quote("FI1") }},
        {{ adapter.quote("FI2") }},
        {{ adapter.quote("FI3") }},
        {{ adapter.quote("FI4") }},
        {{ adapter.quote("FI5") }},
        {{ adapter.quote("FI6") }},
        {{ adapter.quote("FI7") }},
        {{ adapter.quote("FI8") }},
        {{ adapter.quote("FI9") }},
        {{ adapter.quote("FI10") }},
        {{ adapter.quote("FI11") }},
        {{ adapter.quote("FI12") }},
        {{ adapter.quote("FI13") }},
        {{ adapter.quote("FI14") }},
        {{ adapter.quote("FI15") }},
        {{ adapter.quote("FI16") }},
        {{ adapter.quote("FI17") }},
        {{ adapter.quote("FI18") }},
        {{ adapter.quote("FI19") }},
        {{ adapter.quote("FI20") }},
        {{ adapter.quote("FI21") }},
        {{ adapter.quote("FI22") }},
        {{ adapter.quote("FI23") }},
        {{ adapter.quote("FI24") }},
        {{ adapter.quote("FI25") }},
        {{ adapter.quote("FI26") }},
        {{ adapter.quote("FI27") }},
        {{ adapter.quote("FI28") }},
        {{ adapter.quote("FI29") }},
        {{ adapter.quote("FI30") }},
        {{ adapter.quote("FI31") }},
        {{ adapter.quote("FI32") }},
        {{ adapter.quote("FI33") }},
        {{ adapter.quote("FI34") }},
        {{ adapter.quote("FI35") }},
        {{ adapter.quote("FI36") }},
        {{ adapter.quote("FI37") }},
        {{ adapter.quote("FI38") }},
        {{ adapter.quote("FI39") }},
        {{ adapter.quote("FI40") }},
        {{ adapter.quote("FS1") }} as sortiment_type,
        {{ adapter.quote("FS2") }} as visit_cycle,
        {{ adapter.quote("FS3") }} as visit_frequency,
        {{ adapter.quote("FS4") }} as visit_days,
        {{ adapter.quote("FS5") }} as pricelist_id,
        {{ adapter.quote("FS6") }} as listing,
        {{ adapter.quote("FS7") }} as delinst,
        {{ adapter.quote("FS8") }} as additional_name,
        {{ adapter.quote("FS9") }} as sgr,
        {{ adapter.quote("FS10") }} as payer,
        {{ adapter.quote("FS11") }},
        {{ adapter.quote("FS12") }},
        {{ adapter.quote("FS13") }},
        {{ adapter.quote("FS14") }},
        {{ adapter.quote("FS15") }},
        {{ adapter.quote("FS16") }},
        {{ adapter.quote("FS17") }},
        {{ adapter.quote("FS18") }},
        {{ adapter.quote("FS19") }},
        {{ adapter.quote("FS20") }},
        {{ adapter.quote("FB1") }},
        {{ adapter.quote("FB2") }},
        {{ adapter.quote("FB3") }},
        {{ adapter.quote("FB4") }},
        {{ adapter.quote("FB5") }},
        {{ adapter.quote("FB6") }},
        {{ adapter.quote("FB7") }},
        {{ adapter.quote("FB8") }},
        {{ adapter.quote("FB9") }},
        {{ adapter.quote("FB10") }},
        {{ adapter.quote("FB11") }},
        {{ adapter.quote("FB12") }},
        {{ adapter.quote("FB13") }},
        {{ adapter.quote("FB14") }},
        {{ adapter.quote("FB15") }},
        {{ adapter.quote("FB16") }},
        {{ adapter.quote("FB17") }},
        {{ adapter.quote("FB18") }},
        {{ adapter.quote("FB19") }},
        {{ adapter.quote("FB20") }},
        {{ adapter.quote("FD1") }},
        {{ adapter.quote("FD2") }},
        {{ adapter.quote("FD3") }},
        {{ adapter.quote("FD4") }},
        {{ adapter.quote("FD5") }},
        {{ adapter.quote("FD6") }},
        {{ adapter.quote("FD7") }},
        {{ adapter.quote("FD8") }},
        {{ adapter.quote("FD9") }},
        {{ adapter.quote("FD10") }},
        {{ adapter.quote("FD11") }},
        {{ adapter.quote("FD12") }},
        {{ adapter.quote("FD13") }},
        {{ adapter.quote("FD14") }},
        {{ adapter.quote("FD15") }},
        {{ adapter.quote("FD16") }},
        {{ adapter.quote("FD17") }},
        {{ adapter.quote("FD18") }},
        {{ adapter.quote("FD19") }},
        {{ adapter.quote("FD20") }},
        {{ adapter.quote("FN1") }},
        {{ adapter.quote("FN2") }},
        {{ adapter.quote("FN3") }},
        {{ adapter.quote("FN4") }},
        {{ adapter.quote("FN5") }},
        {{ adapter.quote("FN6") }},
        {{ adapter.quote("FN7") }},
        {{ adapter.quote("FN8") }},
        {{ adapter.quote("FN9") }},
        {{ adapter.quote("FN10") }},
        {{ adapter.quote("FN11") }},
        {{ adapter.quote("FN12") }},
        {{ adapter.quote("FN13") }},
        {{ adapter.quote("FN14") }},
        {{ adapter.quote("FN15") }},
        {{ adapter.quote("FN16") }},
        {{ adapter.quote("FN17") }},
        {{ adapter.quote("FN18") }},
        {{ adapter.quote("FN19") }},
        {{ adapter.quote("FN20") }},
        {{ adapter.quote("Valid_From") }},
        {{ adapter.quote("Valid_To") }}

    from source
)
select * from renamed
  